language: python

python:
  - 2.6
  - 2.7

install:
    - pip install requests simplejson nose
    - SOLR_VER="3.6.1"
    - wget -O- "ftp://ftp.fu-berlin.de/unix/www/apache/lucene/solr/${SOLR_VER}/apache-solr-${SOLR_VER}.tgz" | tar xzf -
    - SOLR_PATH=`pwd`/apache-solr-${SOLR_VER}/example

before_script:
    - cd $SOLR_PATH && java -jar start.jar &

script: sleep 10 && python setup.py test

branches:
  only:
    - testing

